//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/funscript.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="funscriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IfunscriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="funscriptParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] funscriptParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="funscriptParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] funscriptParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="funscriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] funscriptParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="funscriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] funscriptParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="funscriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] funscriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="funscriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] funscriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="funscriptParser.sayStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSayStatement([NotNull] funscriptParser.SayStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="funscriptParser.sayStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSayStatement([NotNull] funscriptParser.SayStatementContext context);
}
